from typing import Callable, Any, NewType, Dict, Union, List, Tuple, Sequence
from numpy import ndarray

vector = NewType('vector', ndarray)
matrix = NewType('matrix', ndarray)
Configuration = Dict[str, Union[ndarray, float]]
Bow = List[Tuple[int]]  # generated by gensim.corpora.Dictionary.doc2bow(), efficient representation for sparse vector


basic_types = [type(None), str, bool, int, float, tuple, list, dict]
user_defined_types = [ndarray, Callable[[Any], Any].__origin__, Sequence[Any].__origin__]
elemental = basic_types + user_defined_types


TP_VONMISESFISHER = {
    'model_import': ndarray,
    'level': float,
    'data_import': ndarray,
}

TP_HOTELLING = TP_VONMISESFISHER

TP_BAYES = {
    'x': Sequence[Bow],
    'y': ndarray,
    'gamma': float,
    'validation_rate': float,
    'data_import': Sequence[Bow],
}


if __name__ == '__main__':
    pass
